export const seededDesigns = [
  {
    id: "seed-design-gan-driver",
    slug: "isolated-gan-gate-driver",
    title: "Isolated GaN Gate Driver",
    summary: "A compact dual-channel isolated driver for 650 V GaN half bridges.",
    description:
      "Manufacturing-ready Gerbers, drill files, schematic, BOM, and firmware for a fast isolated half-bridge gate driver.",
    category: "Power electronics",
    license: "CERN-OHL-P-2.0",
    priceCents: 12_900,
    coverImageUrl: null,
    publicationStatus: "published" as const,
    featured: true,
    owner: { displayName: "Thevenin Works" },
    currentRevision: {
      id: "seed-revision-gan-driver-r3",
      version: "3.1.0",
      lifecycleStatus: "published" as const,
      verificationStatus: "verified" as const,
      verifiedAt: "2026-06-18T14:00:00.000Z",
      verificationBadgeExpiresAt: "2027-06-18T14:00:00.000Z",
    },
  },
  {
    id: "seed-design-load",
    slug: "programmable-dc-load",
    title: "Programmable DC Load",
    summary: "A 200 W programmable load with USB-C control and four-wire sensing.",
    description:
      "An open electronic load with a complete enclosure model, calibration procedure, firmware, and production outputs.",
    category: "Test equipment",
    license: "CERN-OHL-P-2.0",
    priceCents: 7_900,
    coverImageUrl: null,
    publicationStatus: "published" as const,
    featured: true,
    owner: { displayName: "Thevenin Works" },
    currentRevision: {
      id: "seed-revision-load-r2",
      version: "2.0.2",
      lifecycleStatus: "published" as const,
      verificationStatus: "in_review" as const,
      verifiedAt: null,
      verificationBadgeExpiresAt: null,
    },
  },
  {
    id: "seed-design-pd-analyzer",
    slug: "usb-c-pd-analyzer",
    title: "USB-C PD Analyzer",
    summary: "Inline USB-C power and protocol measurement with isolated logging.",
    description:
      "A compact inline analyzer for USB Power Delivery development, including source, fabrication outputs, and desktop tooling.",
    category: "Instrumentation",
    license: "CERN-OHL-P-2.0",
    priceCents: 5_900,
    coverImageUrl: null,
    publicationStatus: "published" as const,
    featured: false,
    owner: { displayName: "Thevenin Works" },
    currentRevision: {
      id: "seed-revision-pd-analyzer-r1",
      version: "1.4.0",
      lifecycleStatus: "published" as const,
      verificationStatus: "unverified" as const,
      verifiedAt: null,
      verificationBadgeExpiresAt: null,
    },
  },
] as const;

export const seededProducts = [
  {
    id: "seed-product-scope",
    slug: "four-channel-oscilloscope",
    sku: "TV-SCOPE-4CH-100",
    name: "4-channel 100 MHz oscilloscope",
    description: "Bench oscilloscope with protocol decoding and isolated USB connectivity.",
    category: "Oscilloscopes",
    priceCents: 37900,
    currency: "usd",
    stockStatus: "in_stock" as const,
    imageUrl: null,
    featured: true,
  },
  {
    id: "seed-product-supply",
    slug: "programmable-bench-supply",
    sku: "TV-PSU-60V-10A",
    name: "60 V / 10 A programmable supply",
    description: "Low-noise programmable DC supply with remote sense and USB control.",
    category: "Power supplies",
    priceCents: 28900,
    currency: "usd",
    stockStatus: "in_stock" as const,
    imageUrl: null,
    featured: true,
  },
  {
    id: "seed-product-hotair",
    slug: "precision-hot-air-station",
    sku: "TV-REWORK-700",
    name: "Precision hot-air rework station",
    description: "700 W closed-loop rework station with three nozzles and sleep cradle.",
    category: "Assembly",
    priceCents: 13900,
    currency: "usd",
    stockStatus: "in_stock" as const,
    imageUrl: null,
    featured: false,
  },
  {
    id: "seed-product-meter",
    slug: "true-rms-bench-multimeter",
    sku: "TV-DMM-55000",
    name: "5½ digit bench multimeter",
    description: "True-RMS measurement, four-wire resistance, logging, and SCPI control.",
    category: "Multimeters",
    priceCents: 24900,
    currency: "usd",
    stockStatus: "backorder" as const,
    imageUrl: null,
    featured: false,
  },
] as const;
